# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91ca6c01c023fb11c45ff9fbe891c76e141449bfe956b32603f32329b8d9116a58e2ee65e531e04e5fac1633867e097fdf0fb587fe7113497ff9b0f763029b29

test:
  secret_key_base: 916913385b6ea966ce7f549b5d0ba4a3a95d26092e1467ed472d14a76d58aebbeae6880a5fe1149f9b06ad9563558324e6b0f13db1ec51cec93a8dc076b3a416

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
